### ISSUE TITLE
Cars Searching Search Bar

### ISSUE THREAD

**Issue by mohammedasimahmed** [theashu02/SourceNexus#5]
Hi @theashu02 I want to add a search bar (that has voice search for browsers that support react-speech recognition ) which searches cars from the dataset and returns all cars matching the input

**Comment by theashu02** [comment]
@mohammedasimahmed add some pictures of your project here.

**Comment by mohammedasimahmed** [comment]
The Voice Search functionality seems to be having some issue but you can see the rest of the application here
![Screenshot (5)](https://github.com/theashu02/SourceNexus/assets/123298280/0f2f21a0-2f33-412a-b0d7-2e84845d13ee)
![Screenshot (6)](https://github.com/theashu02/SourceNexus/assets/123298280/8160d12c-5af9-42ed-b706-4e49ff948833)
![Screenshot (7)](https://github.com/theashu02/SourceNexus/assets/123298280/bef7ed78-0f75-4c5c-a89f-cabb260ba721)
![Screenshot (8)](https://github.com/theashu02/SourceNexus/assets/123298280/a3c12e32-6440-4e5d-85e0-fe72188f69f4)
